{% set data = load_setup_py_data() %}

package:
  name: gmx_MMPBSA
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pandas>=1.2.2
    - seaborn>=0.11.1
    - mpi4py>=3.0.3
    - scipy>=1.6.1

  run:
    - python
   
about:
  home: https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA
  license: GPLv3
summary: gmx_MMPBSA is a new tool based on AMBER's MMPBSA.py aiming to perform end-state free energy calculations with GROMACS files.
